jenkins-android:
  build: .
  container_name: jenkins
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
  ports:
    - "50000:50000"
    - "80:8080"
  volumes:
    - /var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
